name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        SDK_URL: [
          "https://downloads.openwrt.org/releases/21.02.1/targets/ramips/mt7621/openwrt-sdk-21.02.1-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz"
         ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Compile
        run: |
          wget ${{ matrix.SDK_URL }}
          tar -xf $(basename ${{ matrix.SDK_URL }})
          cd $(basename -s .tar.xz ${{ matrix.SDK_URL }})
          mkdir -p package/vlmcsd/
          mv $GITHUB_WORKSPACE/Makefile package/vlmcsd/
          mv $GITHUB_WORKSPACE/files package/vlmcsd/
          ./scripts/feeds update packages
          make defconfig
          make package/vlmcsd/compile V=s
          cp $(find -name vlmcsd*.ipk) $GITHUB_WORKSPACE
      - name: Upload package
        uses: actions/upload-artifact@v2.2.4
        with:
          path: vlmcsd*.ipk
